### ISSUE TITLE
Reduce size of the generation part of the library

### ISSUE THREAD

**Issue by mnmkng** [apify/header-generator#2]
Currently, a single dependency of this lib -> `danfo` has over 40MB unpacked. 
<img width="571" alt="image" src="https://user-images.githubusercontent.com/23726914/110795661-61e44100-8277-11eb-933f-82d732b63633.png">

This is too large to be distributed in `got-scraping`, so we need to remove it from distribution. We need to only use those large ML libs in creating the model, but not in its usage.

**Comment by petrpatek** [comment]
It is an outdated issue. It has 5-6MB right now, and we will compress the model files to decrease the size even more in V2.

**Comment by B4nan** [comment]
We still have this file, which is quite meh for a runtime dependency (tbh I don't even like the idea of having it versioned in this repository).

https://github.com/apify/header-generator/blob/master/src/data_files/header-network-definition.json

If it is not needed for runtime, we should think about redesigning this (e.g. have it outside of this repo and download when necessary).

**Comment by petrpatek** [comment]
Yep, this should definitely be improved in V2. This old issue was about ML libraries which are now stripped from the generators. The download process would simplify the release process, or allow updating the models without releasing a new version to be precise. However, I can imagine that the generated model might be broken for some weird reasons and it will stop working immediately for all of all users at the same time.
