### ISSUE TITLE
Make dependencies smaller.

### ISSUE THREAD

**Issue by mnmkng** [apify/header-generator#23]
We still have this file, which is quite meh for a runtime dependency (tbh I don't even like the idea of having it versioned in this repository).

https://github.com/apify/header-generator/blob/master/src/data_files/header-network-definition.json

If it is not needed for runtime, we should think about redesigning this (e.g. have it outside of this repo and download when necessary).

_Originally posted by @B4nan in https://github.com/apify/header-generator/issues/2#issuecomment-1003964725_

**Comment by petrpatek** [comment]
Closing in favor of #15.
